-- ==============================================================================
-- ZAKHRAFA - SEED ALL MOCK PRODUCTS INTO SUPABASE
-- Run this script in Supabase SQL Editor to populate all catalog products.
-- ==============================================================================


INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'milano-luxury-sofa-set',
  'طقم كنب ميلانو الفاخر (4 قطع)',
  'طقم صالون راقٍ يتكون من أريكة ثلاثية، أريكة ثنائية ومقعدين فرديين. مصنوع من خشب الزان الأحمر الروماني مع حشوات إسفنجية عالية الكثافة وتنجيد قماش مخملي إيطالي مقاوم للبقع.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  14500,
  12900,
  'available_now',
  true,
  'خشب زان',
  'قماش مخمل',
  'بيج',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'arcadia-corner-sofa',
  'كنبة زاوية أركاديا المودرن',
  'كنبة زاوية واسعة ومريحة للغاية، بتصميم نورديك أوروبي معاصر، أرجل من الستانلس ستيل الذهبي وقماش بوكليه ناعم يمنح الغرفة دفئاً استثنائياً.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  9800,
  8400,
  'available_now',
  true,
  'قماش بوكليه',
  'ستانلس ستيل',
  'أوف وايت',
  '310 عرض × 180 عمق × 80 ارتفاع سم',
  310,
  180,
  80,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أوف وايت', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'imperial-velvet-armchair',
  'فوتيه إمبريال المخملي',
  'كرسي مفرد بذراعين بتصميم كلاسيكي مدمج مع خطوط مودرن أنيقة، قماش مخملي بلون زيتي عميق مع إطار خشب زان وتفاصيل نحاسية متقنة.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  3200,
  2850,
  'available_now',
  false,
  'خشب زان',
  'قماش مخمل',
  'أخضر زيتي',
  '85 عرض × 85 عمق × 95 ارتفاع سم',
  85,
  85,
  95,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أخضر زيتي', 'كحلي', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'florence-classic-salon',
  'صالون فلورنسا الكلاسيكي الملكي',
  'صالون ملكي بحفر يدوي دقيق على خشب الزان مع لمسات أوراق الذهب المعتق، أقمشة دمشقية فاخرة ووسائد مطرزة يدوياً.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  18900,
  NULL,
  'made_to_order',
  false,
  'خشب زان',
  'أوراق ذهب',
  'ذهبي / بيج',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['ذهبي', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1512212621149-107ffe572d2f?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'verona-minimalist-sofa',
  'أريكة فيرونا المودرن ثلاثية',
  'أريكة مودرن بتصميم ناعم ومريح للمنازل العصرية، قماش كتان هولندي مقاوم للبقع مع وسائد محشوة بريش النعام الصناعي.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  6400,
  NULL,
  'available_now',
  false,
  'خشب زان',
  'كتان طبيعي',
  'رمادي',
  '225 عرض × 90 عمق × 82 ارتفاع سم',
  225,
  90,
  82,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['رمادي', 'كحلي', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'nordic-lounge-chair-leather',
  'كرسي استرخاء لاونج جلد طبيعي',
  'كرسي لاونج مع مسند قدم منفصل، مصنوع من جلد إيطالي طبيعي عالي الجودة مع هيكل خشب الجوز وقاعدة دوارة من الألمنيوم المصقول.',
  (SELECT id FROM public.categories WHERE slug = 'living-rooms' LIMIT 1),
  4900,
  NULL,
  'available_now',
  false,
  'جلد طبيعي',
  'خشب جوز',
  'بني',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بني', 'أسود']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1580481077195-c324c43a04a4?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'marbella-marble-dining-table',
  'طاولة طعام ماربيلا رخام إيطالي (8 كراسي)',
  'طاولة طعام فاخرة بسطح رخام طبيعي كلكتا معالج ضد البقع، قاعدة معدنية بتشطيب برونزي مطفي، مع 8 كراسي مريحة بتنجيد مخملي ناعم.',
  (SELECT id FROM public.categories WHERE slug = 'dining-rooms' LIMIT 1),
  16500,
  14800,
  'available_now',
  true,
  'رخام طبيعي',
  'ستانلس ستيل',
  'بيج / ذهبي',
  '260 عرض × 110 عمق × 78 ارتفاع سم',
  260,
  110,
  78,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1617806118233-18e1de247200?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'valencia-oak-dining-set',
  'طقم سفرة فالنسيا خشب بلوط صلب (6 كراسي)',
  'طاولة طعام دافئة مصنعة من خشب البلوط الطبيعي بتشطيب شمعي مطفي يبرز جمال التموجات الخشبية، مع كراسي مريحة بقماش طبيعي محايد.',
  (SELECT id FROM public.categories WHERE slug = 'dining-rooms' LIMIT 1),
  11200,
  NULL,
  'available_now',
  false,
  'خشب بلوط',
  'كتان طبيعي',
  'بني طبيعي',
  '210 عرض × 100 عمق × 77 ارتفاع سم',
  210,
  100,
  77,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بني طبيعي', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1577140917170-285929fb55b7?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'verona-luxury-buffet',
  'بوفيه سفرة فيرونا رخام وخشب جوز',
  'خزانة بوفيه أنيقة بـ 4 أبواب مضلعة من خشب الجوز وسطح من الرخام الأسود المارق، مع تفاصيل أرفف داخلية ومفصلات إغلاق هادئ ألمانية.',
  (SELECT id FROM public.categories WHERE slug = 'dining-rooms' LIMIT 1),
  7900,
  NULL,
  'made_to_order',
  false,
  'خشب جوز',
  'رخام طبيعي',
  'بني داكن',
  '200 عرض × 48 عمق × 85 ارتفاع سم',
  200,
  48,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بني داكن']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'monaco-round-dining-table',
  'طاولة طعام موناكو دائرية (6 أشخاص)',
  'طاولة طعام دائرية قطر 150 سم، مع قاعدة خشبية نحتية مضلعة وسطح متين من الرخام الإسباني الرمادي، مثالية للتجمعات العائلية الحميمة.',
  (SELECT id FROM public.categories WHERE slug = 'dining-rooms' LIMIT 1),
  8600,
  NULL,
  'available_now',
  false,
  'رخام طبيعي',
  'خشب زان',
  'رمادي / بيج',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['رمادي', 'بيج']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'siena-dining-chairs-pair',
  'زوج كراسي سفرة سيينا بظهر منحني',
  'زوج كراسي سفرة بتصميم عصري مريح، أرجل من خشب الزان الأسود وقماش تنجيد مخملي ناعم الملمس متوفر بخيارات لونية متعددة.',
  (SELECT id FROM public.categories WHERE slug = 'dining-rooms' LIMIT 1),
  2400,
  NULL,
  'available_now',
  false,
  'خشب زان',
  'قماش مخمل',
  'أخضر زيتي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أخضر زيتي', 'بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1580481077195-c324c43a04a4?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'aurora-king-bed-set',
  'غرفة نوم أورورا الفاخرة (كينج)',
  'غرفة نوم متكاملة تتضمن سرير كينج بظهر قماشي كابيتونيه فاخر ممتد، زوج كمودينات، تسريحة مع مرآة بإضاءة ليد مخفية ودولاب ملابس واسع.',
  (SELECT id FROM public.categories WHERE slug = 'bedrooms' LIMIT 1),
  22000,
  19500,
  'available_now',
  true,
  'خشب زان',
  'قماش مخمل',
  'بيج هادئ',
  '210 عرض × 220 عمق × 140 ارتفاع سم',
  210,
  220,
  140,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=1000&auto=format&fit=crop', 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1000&auto=format&fit=crop', 'https://images.unsplash.com/photo-1582582621959-48d27397dc69?q=80&w=1000&auto=format&fit=crop', 'https://images.unsplash.com/photo-1558997519-83ea9252edf8?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'serena-floating-bed',
  'سرير سيرينا المودرن بتصميم عائم',
  'سرير مودرن بتصميم عائم مبتكر وإضاءة سفلية خافتة، لوح رأس عريض مدمج به طاولات سرير جانبية مع شواحن لاسلكية ذكية.',
  (SELECT id FROM public.categories WHERE slug = 'bedrooms' LIMIT 1),
  8900,
  7600,
  'made_to_order',
  false,
  'خشب جوز',
  'ستانلس ستيل',
  'بني جوزي',
  '200 عرض × 215 عمق × 110 ارتفاع سم',
  200,
  215,
  110,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بني جوزي', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'palermo-velvet-bench',
  'بنش نهاية السرير باليرمو مخملي',
  'مقعد بنش أنيق يوضع عند نهاية السرير أو في المداخل، تنجيد مخملي كابيتونيه ناعم مع قاعدة ذهبية من الستانلس ستيل المقاوم.',
  (SELECT id FROM public.categories WHERE slug = 'bedrooms' LIMIT 1),
  2100,
  NULL,
  'available_now',
  false,
  'قماش مخمل',
  'ستانلس ستيل',
  'كحلي',
  '140 عرض × 45 عمق × 48 ارتفاع سم',
  140,
  45,
  48,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['كحلي', 'بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1582582621959-48d27397dc69?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'clarion-luxury-wardrobe',
  'دولاب ملابس كلاريون زجاج مدخن وإضاءة',
  'دولاب ملابس فخم بأبواب زجاجية مدخنة وإطارات ألمنيوم سوداء نحيفة، تقسيمات داخلية مخصصة للحقائب والساعات والإكسسوارات مع إضاءة ذكية.',
  (SELECT id FROM public.categories WHERE slug = 'bedrooms' LIMIT 1),
  15400,
  NULL,
  'made_to_order',
  false,
  'ألمنيوم',
  'زجاج مدخن',
  'رمادي فحمي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['رمادي فحمي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1558997519-83ea9252edf8?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'como-nightstand-pair',
  'زوج كمودينات كومو بتشطيب رخامي',
  'زوج طاولات سرير جانبية بتصميم أسطواني عصري، درجين بمجرى إغلاق هادئ وسطح رخامي مستدير مقاوم للخدوش.',
  (SELECT id FROM public.categories WHERE slug = 'bedrooms' LIMIT 1),
  3100,
  NULL,
  'available_now',
  false,
  'خشب زان',
  'رخام طبيعي',
  'أوف وايت',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أوف وايت', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1532372320572-cda25653a26d?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'orion-marble-coffee-table-set',
  'طقم طاولات قهوة أوريون المتداخلة (رخام)',
  'طقم يتكون من طاولتين متداخلتين بارتفاعات متفاوتة، سطح رخامي تركي طبيعي وقواعد معدنية مضلعة بتشطيب نحاسي عتيق.',
  (SELECT id FROM public.categories WHERE slug = 'tables-consoles' LIMIT 1),
  4600,
  3950,
  'available_now',
  true,
  'رخام طبيعي',
  'حديد مشغول',
  'أبيض / برونزي',
  '90 عرض × 90 عمق × 45 ارتفاع سم',
  90,
  90,
  45,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أبيض', 'أسود']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'castello-entrance-console',
  'كونسول مدخل كاستيلو الفاخر مع مرآة',
  'كونسول استقبال فخم بتصميم هندسي انسيابي، سطح رخام أسود بورتورو مع قاعدة ذهبية نحتية ومرآة جدارية متناسقة بأشكال غير متماثلة.',
  (SELECT id FROM public.categories WHERE slug = 'tables-consoles' LIMIT 1),
  6200,
  NULL,
  'available_now',
  false,
  'رخام طبيعي',
  'ستانلس ستيل',
  'أسود / ذهبي',
  '140 عرض × 40 عمق × 88 ارتفاع سم',
  140,
  40,
  88,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أسود', 'ذهبي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1538688525198-9b88f6f53126?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'zen-solid-wood-coffee-table',
  'طاولة وسط زن من جذوع الخشب الطبيعي',
  'طاولة قهوة فريدة منحوتة من قطعة خشب تيك صلبة بحوافها الطبيعية الحرة، مما يجعل كل قطعة تحفة فنية لا تتكرر في العالم.',
  (SELECT id FROM public.categories WHERE slug = 'tables-consoles' LIMIT 1),
  5400,
  NULL,
  'available_now',
  false,
  'خشب تيك صلب',
  NULL,
  'بني طبيعي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بني طبيعي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1567016432779-094069958ea5?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'linear-side-table-pair',
  'زوج طاولات خدمة لينير الجانبية',
  'طاولات خدمة جانبية خفيفة وسهلة الحركة بجانب الكنب، بتصميم ذكي ينزلق تحت قاعدة الأريكة لتناول القهوة أو العمل براحة.',
  (SELECT id FROM public.categories WHERE slug = 'tables-consoles' LIMIT 1),
  1850,
  NULL,
  'available_now',
  false,
  'ستانلس ستيل',
  'خشب سنديان',
  'أسود / خشب',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['أسود', 'ذهبي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'venice-sculptural-mirror',
  'مرآة فينيسيا النحتية ذات الإطار الذهبي',
  'مرآة جدارية كبيرة بإطار نحتي مستوحى من أشعة الشمس، مطلي بالذهب العتيق ليعكس الفخامة ويعطي اتساعاً وإضاءة للمداخل والممرات.',
  (SELECT id FROM public.categories WHERE slug = 'decor-accessories' LIMIT 1),
  2900,
  NULL,
  'available_now',
  true,
  'زجاج بلجيكي',
  'معدن مطلي',
  'ذهبي',
  '110 عرض × 5 عمق × 110 ارتفاع سم',
  110,
  5,
  110,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['ذهبي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1618219908412-a29a1bb7b86e?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'nordic-brass-pendant-light',
  'ثريا نورديك نحاسية متدلية مودرن',
  'وحدة إضاءة متدلية بتصميم هندسي معلق فوق طاولات الطعام أو الجلسات، مصنوعة من النحاس الخالص مع كرات زجاجية بيضاء معتمة لإضاءة ناعمة.',
  (SELECT id FROM public.categories WHERE slug = 'decor-accessories' LIMIT 1),
  3600,
  NULL,
  'available_now',
  false,
  'نحاس أصفر',
  'زجاج أوبال',
  'ذهبي مطفي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['ذهبي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'ceramic-sculpture-vases-set',
  'طقم فازات نحتية سيراميك ملمس خشن (3 قطع)',
  'تحف خزفية فنية بدرجات ألوان ترابية محايدة، مصنوعة يدوياً بملمس حبيبي مطفي لإضافة لمسة فنية راقية لطاولات القهوة والرفوف.',
  (SELECT id FROM public.categories WHERE slug = 'decor-accessories' LIMIT 1),
  850,
  NULL,
  'available_now',
  false,
  'سيراميك',
  NULL,
  'بيج رملي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'أبيض']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'abstract-canvas-art-diptych',
  'لوحتان كانفاس تجريدية مع إطار خشب عائم',
  'عمل فني ثنائي بألوان محايدة ولمسات بارزة من معجون الجبس، مشدود ومؤطر بإطار خشب زان عائم لإضفاء رونق على جدران الصالون.',
  (SELECT id FROM public.categories WHERE slug = 'decor-accessories' LIMIT 1),
  2200,
  NULL,
  'available_now',
  false,
  'كانفاس',
  'خشب زان',
  'بيج / أسود',
  '160 عرض × 4 عمق × 100 ارتفاع سم',
  160,
  4,
  100,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'أسود']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'royal-diwan-custom-majlis',
  'مجلس عربي ملكي مخصص بالكامل',
  'تنفيذ مجلس متكامل يشمل الكنب الأرضي أو المرتفع، بانوهات الجدران، طاولات الخدمة والستائر حسب المقاسات والمخطط المعماري لمنزلك.',
  (SELECT id FROM public.categories WHERE slug = 'custom-projects' LIMIT 1),
  NULL,
  NULL,
  'made_to_order',
  true,
  'خشب زان',
  'قماش مخمل',
  'حسب اختيار العميل',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'كحلي', 'أخضر زيتي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'custom-walk-in-closet',
  'غرفة ملابس (دريسنج روم) تفصيل حسب المقاس',
  'تصميم وتنفيذ غرف الملابس المفتوحة والمغلقة بأحدث الإكسسوارات الهيدروليكية، جزيرة وسطى للساعات والمجوهرات، وإضاءة سنسور ذكية.',
  (SELECT id FROM public.categories WHERE slug = 'custom-projects' LIMIT 1),
  NULL,
  NULL,
  'made_to_order',
  false,
  'خشب ألماني',
  'زجاج سيكوريت',
  'رمادي حجري / خشب',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['رمادي', 'بني']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1558997519-83ea9252edf8?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'luxury-tv-wall-cladding',
  'بديل رخام وخشب جداري لوحدة التلفاز',
  'تجاليد جدارية فاخرة لوحدات التلفزيون تجمع بين الرخام المضاء وخشب السنديان المضلع مع مدفأة بخار ديكورية كهربائية ذكية.',
  (SELECT id FROM public.categories WHERE slug = 'custom-projects' LIMIT 1),
  8500,
  NULL,
  'made_to_order',
  false,
  'رخام طبيعي',
  'خشب سنديان',
  'رمادي / بني',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['رمادي', 'بني']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

INSERT INTO public.products (
  slug,
  name,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
)
VALUES (
  'hotel-suite-interior-package',
  'تأثيث أجنحة وشقق فندقية متكاملة',
  'باقة متكاملة لتأثيث الشقق الفاخرة والاستثمارية تشمل غرفة النوم، المعيشة، السفرة وكافة اللمسات التكميلية بجودة تناسب التشغيل طويل الأمد.',
  (SELECT id FROM public.categories WHERE slug = 'custom-projects' LIMIT 1),
  NULL,
  NULL,
  'made_to_order',
  false,
  'خشب زان',
  'أقمشة مضادة للبقع',
  'تشكيلات متناسقة',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240,
  95,
  85,
  true,
  'يرجى التأكد من أن عرض فتحة الباب والمداخل لا يقل عن 85 سم لتسهيل دخول ونقل القطعة بسلاسة.',
  'هيكل خشب زان أحمر طبيعي مجفف حرارياً',
  'قماش تنجيد عالي الكثافة مقاوم للبقع',
  'إسفنج سوفت عالي المرونة كثافة 36 طبقات متعددة',
  'ستانلس ستيل مطلي PVD أو خشب مصمت',
  'مفصلات وسكك إغلاق هادئ Soft-Close مجلفنة',
  5,
  ARRAY['بيج', 'رمادي']::TEXT[],
  ARRAY['https://images.unsplash.com/photo-1561501900-3701fa6a0864?q=80&w=1000&auto=format&fit=crop']::TEXT[]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;
