-- ==============================================================================
-- ZAKHRAFA FURNITURE CATALOG - DUMMYJSON FURNITURE SEED
-- Fetched & Mapped from: https://dummyjson.com/products/category/furniture
-- Run this script in your Supabase SQL Editor to populate the database with real products
-- ==============================================================================

-- 1. Insert Annibale Colombo Bed (Bedrooms)
INSERT INTO public.products (
  name,
  slug,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
) VALUES (
  'سرير أنيبالي كولومبو الفاخر - Annibale Colombo Bed',
  'annibale-colombo-bed',
  'سرير إيطالي فخم ومريح مصمم بعناية فائقة بأرقى المواد والخامات المتينة، يمنح غرفة نومك طابعاً ملكياً وعصرياً فريداً مع ظهر مبطن ومريح للجلسات المسائية.',
  '7e8cbe3c-0477-4371-9da9-f9452fd5ecf1',
  18999.00,
  17370.00,
  'available_now',
  true,
  'خشب زان طبيعي صلب',
  'تنجيد مخملي إيطالي فاخر',
  'بني كلاسيكي',
  '200 عرض × 210 عمق × 130 ارتفاع سم',
  200.00,
  210.00,
  130.00,
  true,
  'يناسب المراتب مقاس كينج (190×200 سم). يتطلب ممر مدخل بعرض لا يقل عن 85 سم.',
  'خشب زان أحمر طبيعي مجفف حرارياً ومقاوم للتسوس والرطوبة',
  'قماش مخمل إيطالي ناعم معالج ضد السوائل والبقع',
  'إسفنج سوفت عالي الكثافة 36 لدعم الظهر والفقرات',
  'أرجل خشبية مصمتة بلون جوزي مطعم بلمسات برونزية',
  'وصلات وزوايا فولاذية صامتة ومقاومة للاهتزاز',
  5,
  ARRAY['بني كلاسيكي', 'عاجي بيج', 'رمادي ملكي'],
  ARRAY[
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'
  ]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

-- 2. Insert Annibale Colombo Sofa (Living Rooms)
INSERT INTO public.products (
  name,
  slug,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
) VALUES (
  'كنبة أنيبالي كولومبو الفاخرة - Annibale Colombo Sofa',
  'annibale-colombo-sofa',
  'كنبة مودرن راقية تجمع بين الراحة القصوى والتصميم المعماري المتناسق، مزودة بتنجيد فخم ومساند واسعة لتكون القطعة المركزية المضيئة في صالونك أو غرفة معيشتك.',
  'cecfbc32-8475-4faf-8a8e-a1316a0cb5fd',
  24999.00,
  21400.00,
  'available_now',
  true,
  'خشب زان روماني مبخر',
  'قماش بوكليه تركي فاخر',
  'عاجي وذهبي',
  '240 عرض × 95 عمق × 85 ارتفاع سم',
  240.00,
  95.00,
  85.00,
  true,
  'تناسب الصالونات وغرف المعيشة الواسعة. تحتاج مساحة لا تقل عن 260 سم على الجدار الرئيسي.',
  'خشب زان روماني مبخر معالج ومقاوم للانحناء',
  'قماش بوكليه ناعم إيطالي معالج ضد التجعد والاهتراء',
  'إسفنج مرن هيدروليكي كثافة 36 مع وسائد سفلية من الريش المعقم',
  'قواعد ستانلس ستيل مطلي PVD ذهبي مقاوم للصدأ',
  'أحزمة وتثبيت إيطالي مرن عالي التحمل',
  5,
  ARRAY['عاجي وذهبي', 'رمادي فاتح', 'أخضر زمردي'],
  ARRAY[
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/3.webp'
  ]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

-- 3. Insert Bedside Table African Cherry (Tables & Consoles)
INSERT INTO public.products (
  name,
  slug,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
) VALUES (
  'طاولة جانبية من خشب الكرز الأفريقي - Bedside Table African Cherry',
  'bedside-table-african-cherry',
  'طاولة سرير وكمودينو جانبي أنيق مصنوع من خشب الكرز الأفريقي الطبيعي مع درج تخزين سلس، يوفر مساحة مريحة للمقتنيات ومصباح الإضاءة بلمسة دافئة وعصرية.',
  'ad16df0d-5b7c-479d-bc66-a195fc9937db',
  4500.00,
  3650.00,
  'available_now',
  true,
  'خشب كرز أفريقي طبيعي',
  'مقابض نحاس معتق',
  'كرزي طبيعي دافئ',
  '55 عرض × 45 عمق × 60 ارتفاع سم',
  55.00,
  45.00,
  60.00,
  true,
  'تصميم مدمج ومثالي لجانبي السرير أو زوايا غرف المعيشة بجانب الفوتيهات.',
  'خشب كرز أفريقي مصمت مجفف مع حماية ورنيش مطفي',
  'بدون قماش تنجيد',
  'لا يوجد',
  'أرجل خشب كرز مصمتة مدعمة',
  'مجاري وسكك إغلاق ناعم هيدروليكية ألمانية الصنع',
  3,
  ARRAY['كرزي طبيعي دافئ', 'جوزي غامق', 'بني طبيعي'],
  ARRAY[
    'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/3.webp'
  ]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

-- 4. Insert Knoll Saarinen Executive Conference Chair (Dining Rooms)
INSERT INTO public.products (
  name,
  slug,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
) VALUES (
  'كرسي نول سارينين الفاخر - Knoll Saarinen Chair',
  'knoll-saarinen-executive-conference-chair',
  'تحفة كلاسيكية خالدة بتصميم انسيابي مريح يدعم الظهر بدقة. يلائم طاولات السفرة الفاخرة، المكاتب التنفيذية، وقاعات الاجتماعات الراقية.',
  'fc0dd3eb-ee24-4a38-bc85-3f6bfa4f77a4',
  5800.00,
  5200.00,
  'available_now',
  false,
  'هيكل ستانلس ستيل معزز',
  'قماش صوف كريب عالي المتانة',
  'رمادي فحمي',
  '65 عرض × 60 عمق × 80 ارتفاع سم',
  65.00,
  60.00,
  80.00,
  true,
  'ارتفاع المقعد عن الأرض 48 سم، متوافق مع كافة طاولات الطعام القياسية.',
  'هيكل داخلي مقوى من الألياف والخشب الصلب',
  'قماش صوف منسوج عالي التحمل ضد الاحتكاك اليومي',
  'إسفنج قولبة باردة عالي المرونة ومريح جداً',
  'أرجل ستانلس ستيل مصقول كروم لامع مضاد للخدش',
  'مثبتات وقواعد حماية للأرضيات والباركيه',
  3,
  ARRAY['رمادي فحمي', 'أزرق كحلي', 'بيج كريمي'],
  ARRAY[
    'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/3.webp'
  ]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;

-- 5. Insert Wooden Bathroom Sink With Mirror (Decor & Accessories)
INSERT INTO public.products (
  name,
  slug,
  description,
  category_id,
  original_price,
  discount_price,
  availability_status,
  is_featured,
  material_primary,
  material_secondary,
  color,
  dimensions,
  width,
  depth,
  height,
  custom_dimensions_available,
  space_guide_notes,
  wood_type,
  fabric_type,
  foam_density,
  legs_type,
  hardware_type,
  warranty_years,
  available_colors,
  images
) VALUES (
  'وحدة حوض خشبية مع مرآة - Wooden Bathroom Sink With Mirror',
  'wooden-bathroom-sink-with-mirror',
  'وحدة ديكور استثنائية من الخشب الطبيعي المعالج بالراتنج العازل مع مرآة مطابقة، تضفي لمسة فندقية ساحرة على الحمامات وغرف الضيوف.',
  '6605f773-6018-4509-8450-6311e9da527e',
  9200.00,
  8400.00,
  'made_to_order',
  false,
  'خشب تيك طبيعي معالج بالراتنج',
  'زجاج كريستال بلجيكي فائق النقاء',
  'بلوط طبيعي',
  '90 عرض × 50 عمق × 85 ارتفاع سم',
  90.00,
  50.00,
  85.00,
  true,
  'مجهزة بفتحات تمديدات السباكة القياسية. مقاس المرآة 80×60 سم.',
  'خشب تيك أو آرو طبيعي معالج بطبقات عزل إيبوكسي مقاوم للماء بنسبة 100%',
  'بدون قماش تنجيد',
  'لا يوجد',
  'قواعد خشبية معالجة أو تثبيت معلق على الجدار',
  'إكسسوارات تعليق ستانلس ستيل مخفية شديدة المتانة',
  5,
  ARRAY['بلوط طبيعي', 'جوزي مدخن'],
  ARRAY[
    'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/3.webp'
  ]
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_id = EXCLUDED.category_id,
  original_price = EXCLUDED.original_price,
  discount_price = EXCLUDED.discount_price,
  availability_status = EXCLUDED.availability_status,
  is_featured = EXCLUDED.is_featured,
  material_primary = EXCLUDED.material_primary,
  material_secondary = EXCLUDED.material_secondary,
  color = EXCLUDED.color,
  dimensions = EXCLUDED.dimensions,
  width = EXCLUDED.width,
  depth = EXCLUDED.depth,
  height = EXCLUDED.height,
  custom_dimensions_available = EXCLUDED.custom_dimensions_available,
  space_guide_notes = EXCLUDED.space_guide_notes,
  wood_type = EXCLUDED.wood_type,
  fabric_type = EXCLUDED.fabric_type,
  foam_density = EXCLUDED.foam_density,
  legs_type = EXCLUDED.legs_type,
  hardware_type = EXCLUDED.hardware_type,
  warranty_years = EXCLUDED.warranty_years,
  available_colors = EXCLUDED.available_colors,
  images = EXCLUDED.images;
